Repository AvgBlank/URLShortener, pull requests merged in 2024-10, with the labels that each got.

#6 Fix #2: Add install scripts
  README.md
  install.bat
  install.sh
  start.bat
  start.sh
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2024

#10 Fix #3 Containerized the application using Docker
  Dockerfile
  README.md
  docker-compose.yml
Labels: enhancement, hacktoberfest, hacktoberfest2024

#5 Fix #4: Create USER_GUIDE.md
  USER_GUIDE.md
Labels: documentation, enhancement, hacktoberfest, hacktoberfest2024

#18 Fix #11: Added Login with Google functionality that redirects to /stats page after Login
  app.py
  requirements.txt
  templates/index.html
  templates/stats.html
Labels: enhancement, hacktoberfest, hacktoberfest2024

#17 Fix #12: Fix 404 Error for GitHub Link, Correct Timestamp Display, and Update Post-Login Redirect to Generate URL Page
  app.py
  requirements.txt
  templates/404.html
  templates/generateurl.html
  templates/index.html
  templates/login.html
  templates/signup.html
  templates/stats.html
Labels: bug, enhancement, good first issue, hacktoberfest, hacktoberfest2024

#20 Login and SignUp with Google
  templates/login.html
  templates/signup.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2024

#26 Fix #15: Add feature to delete URL history
  app.py
  templates/stats.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2024

#29 Enhancement: Improve index.html
  templates/index.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2024

#36 Documentation: Enhance README.md
  README.md
Labels: documentation, enhancement, good first issue, hacktoberfest, hacktoberfest2024
